name: EPointsSC
main: me.chr1s0143.EPointsSC.epoints
version: 1.0
author: Chris Hall
description: Simple plugin for non-ops to credit winners of games in spleef/parkour etc with enjin points

commands:
  epoints:
    description: epoints (playername)

permissions:
  epoints.use:
    description: Gives access to all epoints commands.